wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1656243539
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 16
      4: 3.6.13
      5: 0.12.18
      6: 4.14.1
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 2040
early_stop_epoch_threshold:
  desc: null
  value: 4
lr:
  desc: null
  value: 1.0e-05
max_epochs:
  desc: null
  value: 50
model:
  desc: null
  value: mm_baseline_cls
wd:
  desc: null
  value: 0.0001
