wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1655902553
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      4: 3.6.13
      5: 0.12.18
      6: 4.14.1
      8:
      - 3
      - 5
